apiVersion: v1
kind: Service
metadata:
  namespace: freshcredit
  name: blockiq
spec:
  ports:
    - name: alice
      port: 40333
      targetPort: 40333
      protocol: TCP
    - name: ws-port
      port: 8844
      targetPort: 8844
      protocol: TCP
    - name: wasm-port
      port: 30343
      targetPort: 30343
      protocol: TCP
    - name: wasm-ws-port
      port: 9977
      targetPort: 9977
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: blockiq
